# Base configs
baseurl: "http://palermog.github.io/photography"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Gregory Palermo"
subtitle: ""
author: "Gregory Palermo"
header:
 title: "Photography"
 subtitle: "by Gregory Palermo"
footer:
 name: "Hey there, my name is Ram"
 bio: "*insert bio*"
 github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork rampatra's repo on github</a> ;)"
web_design: "AJ"
social_urls:
  #facebook:
  twitter: "https://www.twitter.com/gregory_palermo"
  instagram: "https://www.instagram.com/gregjp48"
  github: "https://www.github.com/gregjp48"
