# Base configs
baseurl: "http://palermog.github.io/photography"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Gregory Palermo"
subtitle:
author: "Gregory Palermo"
header:
 title: "Photography"
 subtitle: "by Gregory Palermo"
footer:
 name: "Hi, I'm Greg, and I'm a graduate student and amateur photographer."
 bio: "Thanks for checking out my work!"
 github: "Credit to Ram Patra for the <a href=\"https://github.com/rampatra/photography">site template</a>."
web_design: "AJ"
social_urls:
  #facebook:
  twitter: "https://www.twitter.com/gregory_palermo"
  instagram: "https://www.instagram.com/gregjp48"
  github: "https://www.github.com/gregjp48"
